services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: immo_db
      POSTGRES_USER: immo_user
      POSTGRES_PASSWORD: immo_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: